### ISSUE TITLE
Cannot add pdParticles to project

### ISSUE THREAD

**Issue by GammaGames** [toyboxpy/toybox.py#8]
idk where the log file is, but here's a bunch of commands I ran

```bash
me@eos:~/Documents/Projects/Playwrite$ toybox version
🧸 toybox.py v1.1.3
me@eos:~/Documents/Projects/Playwrite$ toybox info
Resolving dependencies...
       - github.com/Whitebrim/AnimatedSprite@(>=1.0.0 <2.0.0) -> 1.1.0
       - github.com/NicMagnier/PlaydateSequence@main -> main@3f9679c014a955130e90f85c72075e8635381db5
       - github.com/DidierMalenfant/Signal@(>=1.0.0 <2.0.0) -> 1.1.0
me@eos:~/Documents/Projects/Playwrite$ toybox store content
Currently available in the toystore:
   AnimatedSprite -> https://github.com/Whitebrim/AnimatedSprite
   Aspen -> https://github.com/DidierMalenfant/Aspen
   LDtkImporter -> https://github.com/NicMagnier/PlaydateLDtkImporter
   librif -> https://github.com/risolvipro/librif
   modplayer -> https://github.com/DidierMalenfant/modplayer
   pdbase -> https://github.com/DidierMalenfant/pdbase
   playbox2d -> https://github.com/DidierMalenfant/playbox2d
   Plupdate -> https://github.com/DidierMalenfant/Plupdate
   RobkohrFont -> https://github.com/RobKohr/robkohr-mono-5x8-font-for-playdate
   Sequence -> https://github.com/NicMagnier/PlaydateSequence
   Signal -> https://github.com/DidierMalenfant/Signal.git
   TileMap -> https://github.com/DidierMalenfant/TileMap
   TiledUp -> https://github.com/DidierMalenfant/TiledUp
   pdParticles -> https://github.com/PossiblyAxolotl/pdParticles
me@eos:~/Documents/Projects/Playwrite$ toybox add pdParticles
can only concatenate str (not "NoneType") to str
me@eos:~/Documents/Projects/Playwrite$ toybox info
Resolving dependencies...
'NoneType' object has no attribute 'split'
me@eos:~/Documents/Projects/Playwrite$ toybox update
Resolving dependencies...
'NoneType' object has no attribute 'split'
me@eos:~/Documents/Projects/Playwrite$ toybox remove pdParticles
Removed a dependency for 'pdParticles'.
me@eos:~/Documents/Projects/Playwrite$ toybox info
Resolving dependencies...
       - github.com/Whitebrim/AnimatedSprite@(>=1.0.0 <2.0.0) -> 1.1.0
       - github.com/NicMagnier/PlaydateSequence@main -> main@3f9679c014a955130e90f85c72075e8635381db5
       - github.com/DidierMalenfant/Signal@(>=1.0.0 <2.0.0) -> 1.1.0
me@eos:~/Documents/Projects/Playwrite$ toybox update
Resolving dependencies...
Finished.
```

**Comment by DidierMalenfant** [comment]
Thanks for submitting this.

Can you update your toybox to v1.2.0? I added a new options to display more debugging info.
```
pip install toyboxpy --upgrade
```

Then try again adding the toy box but this time with:
```
toybox --debug add pdParticles
```

and let me know back here what the error message looks like now.

**Comment by GammaGames** [comment]
```
Enabling debugging information.
Updating the toystore...
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.8/site-packages/toybox/__main__.py", line 22, in main
    Toybox(sys.argv[1:]).main()
  File "/home/me/.local/lib/python3.8/site-packages/toybox/toybox.py", line 114, in main
    method()
  File "/home/me/.local/lib/python3.8/site-packages/toybox/toybox.py", line 277, in addDependency
    info_string += '@' + at
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by DidierMalenfant** [comment]
Thank you! Version 1.2.1 should fix this... give it a try and let me know.

**Comment by GammaGames** [comment]
It did, thank you so much!
